// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sycfwmjmxfwodmjqtrbt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5Y2Z3bWpteGZ3b2RtanF0cmJ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDU3MTUsImV4cCI6MjA2MDIyMTcxNX0.pMrN6ppOo13jbTpGFPMFF12sPrlBLS1CxOWxvzgUHQg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);